=== AntonKabatut/EpamPractices/Practice6/src/input.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="Beers">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="Beer" type="AbsBeer" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="AbsBeer" abstract="true"/>

    <xsd:complexType name="NonAlcBeer">

            <xsd:complexContent>
                <xsd:extension base="AbsBeer">

                    <xsd:sequence>
                        <xsd:element name="Name" type="xsd:string"/>
                        <xsd:element name="Type" type="xsd:string"/>
                        <xsd:element name="Al" type="xsd:boolean" fixed="false"/>
                        <xsd:element name="Manufacturer" type="xsd:string"/>
                        <xsd:sequence>
                            <xsd:element name="Ingredients" type="Ingredients"/>
                        </xsd:sequence>
                        <xsd:element name="Transparency" type="xsd:string"/>
                        <xsd:element name="Filter" type="xsd:boolean"/>
                        <xsd:element name="NutritionalValue" type="xsd:string"/>
                        <xsd:element name="Spill" type="Sposob"/>
                    </xsd:sequence>

                </xsd:extension>
            </xsd:complexContent>

    </xsd:complexType>

    <xsd:complexType name="AlcBeer">
        <xsd:complexContent>
            <xsd:extension base="AbsBeer">

                <xsd:sequence>
                    <xsd:element name="Name" type="xsd:string"/>
                    <xsd:element name="Type" type="xsd:string"/>
                    <xsd:element name="Al" type="xsd:boolean" fixed="true"/>
                    <xsd:element name="Manufacturer" type="xsd:string"/>
                    <xsd:sequence>
                        <xsd:element name="Ingredients" type="Ingredients"/>
                    </xsd:sequence>
                    <xsd:element name="Turnover" type="xsd:string"/>
                    <xsd:element name="Transparency" type="xsd:string"/>
                    <xsd:element name="Filter" type="xsd:boolean"/>
                    <xsd:element name="NutritionalValue" type="xsd:string"/>
                    <xsd:element name="Spill" type="Sposob"/>
                </xsd:sequence>

            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>



    <xsd:complexType name="Ingredients" mixed="true">
        <xsd:sequence>
            <xsd:element name="Name" type="xsd:string" minOccurs="3" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Enumeration">
        <xsd:sequence>
            <xsd:element name="type" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Sposob">
        <xsd:sequence>
            <xsd:element name="objem" type="xsd:string"/>
            <xsd:element name="material" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== AntonKabatut/EpamPractices/Practice6/src/input.xml
<?xml version="1.0" encoding="UTF-8"?>
<Beers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="input.xsd">

    <Beer xsi:type="NonAlcBeer">
        <Name>bud</Name>
        <Type>svetloe</Type>
        <Al>false</Al>
        <Manufacturer>companyPivo</Manufacturer>
        <Ingredients>
            <Name>water</Name>
            <Name>weed</Name>
            <Name>sugar</Name>
        </Ingredients>
        <Transparency>12323</Transparency>
        <Filter>true</Filter>
        <NutritionalValue>123213</NutritionalValue>
        <Spill>
            <objem>0,5</objem>
            <material>steklo</material>
        </Spill>
    </Beer>

    <Beer xsi:type="AlcBeer">
        <Name>astaropramen</Name>
        <Type>dark</Type>
        <Al>true</Al>
        <Manufacturer>companyPivo</Manufacturer>
        <Ingredients>
            <Name>water</Name>
            <Name>weed</Name>
            <Name>sugar</Name>
        </Ingredients>
        <Turnover>8</Turnover>
        <Transparency>31413413</Transparency>
        <Filter>true</Filter>
        <NutritionalValue>45324</NutritionalValue>
        <Spill>
            <objem>0,5</objem>
            <material>steklo</material>
        </Spill>
    </Beer>

</Beers>
